actors: 
  - address: 192.168.178.12:9999
    disable_threshold: 100
    enable_threshold: -100
    duration_minutes: 60
ttys_location: /dev/ttyS0
gpio_location: /dev/gpiochip0
gpio_power_pin: 38 # Pin 35 in Mango PI
